/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animationstudios;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanm
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CambioValores = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        velmaIntro = new javax.swing.JTextField();
        velmaIntro1 = new javax.swing.JTextField();
        velmaIntro2 = new javax.swing.JTextField();
        velmaIntro3 = new javax.swing.JTextField();
        velmaIntro4 = new javax.swing.JTextField();
        velmaIntro5 = new javax.swing.JTextField();
        velmaIntro6 = new javax.swing.JTextField();
        velmaIntro7 = new javax.swing.JTextField();
        velmaIntro8 = new javax.swing.JTextField();
        velmaIntro9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        velmaIntro15 = new javax.swing.JTextField();
        velmaIntro16 = new javax.swing.JTextField();
        velmaIntro17 = new javax.swing.JTextField();
        velmaIntro18 = new javax.swing.JTextField();
        velmaIntro19 = new javax.swing.JTextField();
        velmaIntro20 = new javax.swing.JTextField();
        velmaIntro21 = new javax.swing.JTextField();
        velmaIntro22 = new javax.swing.JTextField();
        velmaIntro23 = new javax.swing.JTextField();
        velmaIntro24 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        velmaIntro25 = new javax.swing.JTextField();
        velmaIntro26 = new javax.swing.JTextField();
        velmaIntro27 = new javax.swing.JTextField();
        velmaIntro28 = new javax.swing.JTextField();
        velmaIntro29 = new javax.swing.JTextField();
        velmaIntro30 = new javax.swing.JTextField();
        velmaIntro31 = new javax.swing.JTextField();
        velmaIntro32 = new javax.swing.JTextField();
        velmaIntro33 = new javax.swing.JTextField();
        velmaIntro34 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        velmaIntro10 = new javax.swing.JTextField();
        velmaIntro11 = new javax.swing.JTextField();
        velmaIntro12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        velmaIntro13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        velmaIntro35 = new javax.swing.JTextField();
        velmaIntro36 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        velmaIntro37 = new javax.swing.JTextField();
        velmaIntro38 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        velmaIntro39 = new javax.swing.JTextField();
        velmaIntro40 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        velmaIntro41 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        velmaIntro43 = new javax.swing.JTextField();
        velmaIntro44 = new javax.swing.JTextField();
        velmaIntroDown = new javax.swing.JButton();
        velmaIntroDown1 = new javax.swing.JButton();
        velmaIntroDown2 = new javax.swing.JButton();
        velmaIntroDown3 = new javax.swing.JButton();
        velmaIntroDown4 = new javax.swing.JButton();
        velmaIntroDown5 = new javax.swing.JButton();
        velmaIntroDown6 = new javax.swing.JButton();
        velmaIntroDown7 = new javax.swing.JButton();
        velmaIntroDown8 = new javax.swing.JButton();
        velmaIntroDown9 = new javax.swing.JButton();
        velmaIntroDown10 = new javax.swing.JButton();
        velmaIntroDown11 = new javax.swing.JButton();
        velmaCierreUp = new javax.swing.JButton();
        velmaCierreUp1 = new javax.swing.JButton();
        velmaCierreUp2 = new javax.swing.JButton();
        velmaCierreUp3 = new javax.swing.JButton();
        velmaCierreUp4 = new javax.swing.JButton();
        velmaCierreUp5 = new javax.swing.JButton();
        velmaCierreUp6 = new javax.swing.JButton();
        velmaCierreUp7 = new javax.swing.JButton();
        velmaCierreUp8 = new javax.swing.JButton();
        velmaCierreUp9 = new javax.swing.JButton();
        velmaCierreUp10 = new javax.swing.JButton();
        velmaCierreUp11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DISEÑADORES");
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        CambioValores.setText("Colocar Nuevos Valores");
        CambioValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioValoresActionPerformed(evt);
            }
        });
        getContentPane().add(CambioValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jButton2.setText("Iniciar simulacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 140, -1));

        jLabel2.setText("ESTUDIOS DE ANIMACION EN VENEZUELA");
        jLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel2PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 50));

        jLabel4.setText("DIRECTOR");
        jLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel4PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, -1, 30));

        jLabel9.setText("DISNEY CHANEL");
        jLabel9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel9PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        jLabel5.setText("ANIMADORES");
        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 20));

        jLabel6.setText("ACTORES D");
        jLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel6PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        jLabel7.setText("GUIONISTA PT");
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        jLabel8.setText("GUIONISTAS");
        jLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel8PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        jLabel3.setText("DISEÑADORES");
        jLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel3PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, 20));

        jLabel10.setText("STAR CHANEL");
        jLabel10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel10PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, 30));

        jLabel11.setText("ANIMADORES");
        jLabel11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel11PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 20));

        jLabel12.setText("ACTORES D");
        jLabel12.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel12PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 20));

        jLabel13.setText("GUIONISTA PT");
        jLabel13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel13PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, 20));

        jLabel14.setText("GUIONISTAS");
        jLabel14.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel14PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 20));

        velmaIntro.setEditable(false);
        velmaIntro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 40, -1));

        velmaIntro1.setEditable(false);
        velmaIntro1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro1ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 40, -1));

        velmaIntro2.setEditable(false);
        velmaIntro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro2ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 40, -1));

        velmaIntro3.setEditable(false);
        velmaIntro3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro3ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 40, -1));

        velmaIntro4.setEditable(false);
        velmaIntro4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro4ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 40, -1));

        velmaIntro5.setEditable(false);
        velmaIntro5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro5ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 40, -1));

        velmaIntro6.setEditable(false);
        velmaIntro6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro6ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 40, -1));

        velmaIntro7.setEditable(false);
        velmaIntro7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro7ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 40, -1));

        velmaIntro8.setEditable(false);
        velmaIntro8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro8ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, -1));

        velmaIntro9.setEditable(false);
        velmaIntro9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro9ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 40, -1));

        jLabel15.setText("MAX");
        jLabel15.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel15PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 30, 20));

        jLabel21.setText("ESCENARIOS");
        jLabel21.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel21PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 20));

        jLabel22.setText("ANIMACIONES");
        jLabel22.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel22PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 20));

        jLabel23.setText("DOBLAJES");
        jLabel23.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel23PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 20));

        jLabel24.setText("PLOT TWIST");
        jLabel24.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel24PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, 20));

        jLabel25.setText("GUIONES");
        jLabel25.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel25PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 20));

        velmaIntro15.setEditable(false);
        velmaIntro15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro15ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 40, -1));

        velmaIntro16.setEditable(false);
        velmaIntro16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro16ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, -1));

        velmaIntro17.setEditable(false);
        velmaIntro17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro17ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 40, -1));

        velmaIntro18.setEditable(false);
        velmaIntro18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro18ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 40, -1));

        velmaIntro19.setEditable(false);
        velmaIntro19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro19ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 40, -1));

        velmaIntro20.setEditable(false);
        velmaIntro20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro20ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 40, -1));

        velmaIntro21.setEditable(false);
        velmaIntro21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro21ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 40, -1));

        velmaIntro22.setEditable(false);
        velmaIntro22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro22ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 40, -1));

        velmaIntro23.setEditable(false);
        velmaIntro23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro23ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 40, -1));

        velmaIntro24.setEditable(false);
        velmaIntro24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro24ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 40, -1));

        jLabel26.setText("ESCENARIOS");
        jLabel26.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel26PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 20));

        jLabel27.setText("ANIMACIONES");
        jLabel27.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel27PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 20));

        jLabel28.setText("DOBLAJES");
        jLabel28.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel28PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, 20));

        jLabel29.setText("PLOT TWIST");
        jLabel29.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel29PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 20));

        jLabel30.setText("GUIONES");
        jLabel30.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel30PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, 20));

        velmaIntro25.setEditable(false);
        velmaIntro25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro25ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 40, -1));

        velmaIntro26.setEditable(false);
        velmaIntro26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro26ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 40, -1));

        velmaIntro27.setEditable(false);
        velmaIntro27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro27ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 40, -1));

        velmaIntro28.setEditable(false);
        velmaIntro28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro28ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 40, -1));

        velmaIntro29.setEditable(false);
        velmaIntro29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro29ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 40, -1));

        velmaIntro30.setEditable(false);
        velmaIntro30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro30ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro30, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 40, -1));

        velmaIntro31.setEditable(false);
        velmaIntro31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro31ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 40, -1));

        velmaIntro32.setEditable(false);
        velmaIntro32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro32ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 40, -1));

        velmaIntro33.setEditable(false);
        velmaIntro33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro33ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro33, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 40, -1));

        velmaIntro34.setEditable(false);
        velmaIntro34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro34ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 40, -1));

        jLabel16.setText("ENSAMBLADORES");
        jLabel16.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel16PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, 30));

        jLabel17.setText("MAX");
        jLabel17.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel17PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 30, 20));

        jLabel18.setText("TRABAJADORES");
        jLabel18.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel18PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));

        velmaIntro10.setEditable(false);
        velmaIntro10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro10ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        velmaIntro11.setEditable(false);
        velmaIntro11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro11ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        velmaIntro12.setEditable(false);
        velmaIntro12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro12ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 40, -1));

        jLabel19.setText("ENSAMBLADORES");
        jLabel19.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel19PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 30));

        velmaIntro13.setEditable(false);
        velmaIntro13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro13ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        jLabel20.setText("ELEMENTOS DE CAPITULOS");
        jLabel20.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel20PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 30));

        jLabel31.setText("PLOT TWIST");
        jLabel31.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel31PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, 20));

        jLabel32.setText("ESTANDAR");
        jLabel32.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel32PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 20));

        velmaIntro35.setEditable(false);
        velmaIntro35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro35ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 40, -1));

        velmaIntro36.setEditable(false);
        velmaIntro36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro36ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro36, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 40, -1));

        jLabel33.setText("PLOT TWIST");
        jLabel33.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel33PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, -1, 20));

        jLabel34.setText("ESTANDAR");
        jLabel34.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel34PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, 20));

        velmaIntro37.setEditable(false);
        velmaIntro37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro37ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 40, -1));

        velmaIntro38.setEditable(false);
        velmaIntro38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro38ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 40, -1));

        jLabel35.setText("FALTAS");
        jLabel35.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel35PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, -1, 20));

        jLabel36.setText("ACTIVIDAD");
        jLabel36.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel36PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, 20));

        velmaIntro39.setEditable(false);
        velmaIntro39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro39ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro39, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 70, -1));

        velmaIntro40.setEditable(false);
        velmaIntro40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro40ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 70, -1));

        jLabel38.setText("ACTIVIDAD");
        jLabel38.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel38PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, 20));

        velmaIntro41.setEditable(false);
        velmaIntro41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro41ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 80, -1));

        jLabel39.setText("ELEMENTOS DE CAPITULOS");
        jLabel39.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel39PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, 30));

        jLabel40.setText("PROJECT MANAGER");
        jLabel40.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel40PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, 30));

        jLabel41.setText("SALARIO");
        jLabel41.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel41PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, -1, 20));

        jLabel42.setText("DESCUENTO");
        jLabel42.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel42PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, -1, 20));

        velmaIntro43.setEditable(false);
        velmaIntro43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro43ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro43, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 70, -1));

        velmaIntro44.setEditable(false);
        velmaIntro44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro44ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, 70, -1));

        velmaIntroDown.setText("-");
        velmaIntroDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDownActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        velmaIntroDown1.setText("-");
        velmaIntroDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown1ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        velmaIntroDown2.setText("-");
        velmaIntroDown2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown2ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        velmaIntroDown3.setText("-");
        velmaIntroDown3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown3ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        velmaIntroDown4.setText("-");
        velmaIntroDown4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown4ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        velmaIntroDown5.setText("-");
        velmaIntroDown5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown5ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        velmaIntroDown6.setText("-");
        velmaIntroDown6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown6ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        velmaIntroDown7.setText("-");
        velmaIntroDown7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown7ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        velmaIntroDown8.setText("-");
        velmaIntroDown8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown8ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        velmaIntroDown9.setText("-");
        velmaIntroDown9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown9ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        velmaIntroDown10.setText("-");
        velmaIntroDown10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown10ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        velmaIntroDown11.setText("-");
        velmaIntroDown11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntroDown11ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntroDown11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        velmaCierreUp.setText("+");
        velmaCierreUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUpActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        velmaCierreUp1.setText("+");
        velmaCierreUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp1ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        velmaCierreUp2.setText("+");
        velmaCierreUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp2ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        velmaCierreUp3.setText("+");
        velmaCierreUp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp3ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        velmaCierreUp4.setText("+");
        velmaCierreUp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp4ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        velmaCierreUp5.setText("+");
        velmaCierreUp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp5ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        velmaCierreUp6.setText("+");
        velmaCierreUp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp6ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        velmaCierreUp7.setText("+");
        velmaCierreUp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp7ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        velmaCierreUp8.setText("+");
        velmaCierreUp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp8ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        velmaCierreUp9.setText("+");
        velmaCierreUp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp9ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        velmaCierreUp10.setText("+");
        velmaCierreUp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp10ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        velmaCierreUp11.setText("+");
        velmaCierreUp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaCierreUp11ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaCierreUp11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void CambioValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioValoresActionPerformed
        // TODO add your handling code here:
        String inputDuracionDias = JOptionPane.showInputDialog(null, "Ingrese el tiempo que dura un dia en segundos: ");
        String inputCantidadDias = JOptionPane.showInputDialog(null, "Ingrese la cantidad de dias entre lanzamientos: ");
        String inputGuionistas = JOptionPane.showInputDialog(null, "Cantidad de guionistas: ");
        String inputDesigners = JOptionPane.showInputDialog(null, "Cantidad de diseñadores: ");
        String inputAnimadores = JOptionPane.showInputDialog(null, "Cantidad de animadores de personajes: ");
        String inputActoresD = JOptionPane.showInputDialog(null, "Cantidad de actores de doblaje: ");
        String inputGuionistasPT = JOptionPane.showInputDialog(null, "Cantidad de guionistas de Plot twist: ");
        String inputEnsambladores = JOptionPane.showInputDialog(null, "Cantidad de ensambladores: ");
        
        if (Integer.parseInt(inputGuionistas)+Integer.parseInt(inputDesigners)+Integer.parseInt(inputAnimadores)+Integer.parseInt(inputActoresD)+Integer.parseInt(inputGuionistasPT)+Integer.parseInt(inputEnsambladores)>=19) {
            JOptionPane.showMessageDialog(null, "Error, la cantidad de trabajadores y ensambladores no debe ser mayor a 18.");
            this.dispose();
        }
        
        String archivotxt = inputDuracionDias + "//" + inputCantidadDias + "//" + inputGuionistas + "," + inputDesigners + "," + inputAnimadores + "," + inputActoresD + "," + inputGuionistasPT + "//" + inputEnsambladores;
        
        BufferedReader br;
        
        try {
            PrintStream out = new PrintStream(new FileOutputStream("archivo.txt"));
            out.print(archivotxt);
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_CambioValoresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2PropertyChange

    private void jLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4PropertyChange

    private void jLabel9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel9PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9PropertyChange

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5PropertyChange

    private void jLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6PropertyChange

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7PropertyChange

    private void jLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8PropertyChange

    private void jLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3PropertyChange

    private void jLabel10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel10PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10PropertyChange

    private void jLabel11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel11PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11PropertyChange

    private void jLabel12PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel12PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12PropertyChange

    private void jLabel13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel13PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13PropertyChange

    private void jLabel14PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel14PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14PropertyChange

    private void velmaIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroActionPerformed

    private void velmaIntro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro1ActionPerformed

    private void velmaIntro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro2ActionPerformed

    private void velmaIntro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro3ActionPerformed

    private void velmaIntro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro4ActionPerformed

    private void velmaIntro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro5ActionPerformed

    private void velmaIntro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro6ActionPerformed

    private void velmaIntro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro7ActionPerformed

    private void velmaIntro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro8ActionPerformed

    private void velmaIntro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro9ActionPerformed

    private void jLabel15PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel15PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15PropertyChange

    private void jLabel21PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel21PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21PropertyChange

    private void jLabel22PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel22PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22PropertyChange

    private void jLabel23PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel23PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23PropertyChange

    private void jLabel24PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel24PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24PropertyChange

    private void jLabel25PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel25PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25PropertyChange

    private void velmaIntro15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro15ActionPerformed

    private void velmaIntro16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro16ActionPerformed

    private void velmaIntro17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro17ActionPerformed

    private void velmaIntro18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro18ActionPerformed

    private void velmaIntro19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro19ActionPerformed

    private void velmaIntro20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro20ActionPerformed

    private void velmaIntro21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro21ActionPerformed

    private void velmaIntro22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro22ActionPerformed

    private void velmaIntro23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro23ActionPerformed

    private void velmaIntro24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro24ActionPerformed

    private void jLabel26PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel26PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26PropertyChange

    private void jLabel27PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel27PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27PropertyChange

    private void jLabel28PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel28PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28PropertyChange

    private void jLabel29PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel29PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29PropertyChange

    private void jLabel30PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel30PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30PropertyChange

    private void velmaIntro25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro25ActionPerformed

    private void velmaIntro26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro26ActionPerformed

    private void velmaIntro27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro27ActionPerformed

    private void velmaIntro28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro28ActionPerformed

    private void velmaIntro29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro29ActionPerformed

    private void velmaIntro30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro30ActionPerformed

    private void velmaIntro31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro31ActionPerformed

    private void velmaIntro32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro32ActionPerformed

    private void velmaIntro33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro33ActionPerformed

    private void velmaIntro34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro34ActionPerformed

    private void jLabel16PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel16PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16PropertyChange

    private void jLabel17PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel17PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17PropertyChange

    private void jLabel18PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel18PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18PropertyChange

    private void velmaIntro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro10ActionPerformed

    private void velmaIntro11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro11ActionPerformed

    private void velmaIntro12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro12ActionPerformed

    private void jLabel19PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel19PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19PropertyChange

    private void velmaIntro13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro13ActionPerformed

    private void jLabel20PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel20PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20PropertyChange

    private void jLabel31PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel31PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31PropertyChange

    private void jLabel32PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel32PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32PropertyChange

    private void velmaIntro35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro35ActionPerformed

    private void velmaIntro36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro36ActionPerformed

    private void jLabel33PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel33PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33PropertyChange

    private void jLabel34PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel34PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34PropertyChange

    private void velmaIntro37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro37ActionPerformed

    private void velmaIntro38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro38ActionPerformed

    private void jLabel35PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel35PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35PropertyChange

    private void jLabel36PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel36PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36PropertyChange

    private void velmaIntro39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro39ActionPerformed

    private void velmaIntro40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro40ActionPerformed

    private void jLabel38PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel38PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38PropertyChange

    private void velmaIntro41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro41ActionPerformed

    private void jLabel39PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel39PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39PropertyChange

    private void jLabel40PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel40PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40PropertyChange

    private void jLabel41PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel41PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41PropertyChange

    private void jLabel42PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel42PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42PropertyChange

    private void velmaIntro43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro43ActionPerformed

    private void velmaIntro44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro44ActionPerformed

    private void velmaIntroDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDownActionPerformed
        int holderInt = Integer.parseInt(velmaIntro.getText());
        if (holderInt == 1) {
            JOptionPane.showMessageDialog(null, "Los productores no pueden bajar de 1 dado que despiden al Project Manager");
        } else {
            holderInt--;
            velmaIntro.setText(Integer.toString(holderInt));
            tIntro.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaIntroDownActionPerformed

    private void velmaIntroDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown1ActionPerformed

    private void velmaIntroDown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown2ActionPerformed

    private void velmaIntroDown3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown3ActionPerformed

    private void velmaIntroDown4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown4ActionPerformed

    private void velmaIntroDown5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown5ActionPerformed

    private void velmaIntroDown6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown6ActionPerformed

    private void velmaIntroDown7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown7ActionPerformed

    private void velmaIntroDown8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown8ActionPerformed

    private void velmaIntroDown9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown9ActionPerformed

    private void velmaIntroDown10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown10ActionPerformed

    private void velmaIntroDown11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntroDown11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntroDown11ActionPerformed

    private void velmaCierreUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUpActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUpActionPerformed

    private void velmaCierreUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp1ActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUp1ActionPerformed

    private void velmaCierreUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp2ActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUp2ActionPerformed

    private void velmaCierreUp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp3ActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUp3ActionPerformed

    private void velmaCierreUp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp4ActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUp4ActionPerformed

    private void velmaCierreUp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp5ActionPerformed
        if (Integer.parseInt(velmaIntro.getText()) + Integer.parseInt(velmaCreditos.getText()) + Integer.parseInt(velmaInicio.getText()) + Integer.parseInt(velmaCierre.getText()) + Integer.parseInt(velmaPlottwist.getText()) + Integer.parseInt(velmaEnsambladores.getText()) == 11) {
            JOptionPane.showMessageDialog(null, "La cantidad maxima de productores no puede ser mas de 11");

        } else {
            int holderInt = Integer.parseInt(velmaCierre.getText());
            holderInt++;
            velmaCierre.setText(Integer.toString(holderInt));
            tCierre.setNumeroDeProductores(holderInt);
        }
    }//GEN-LAST:event_velmaCierreUp5ActionPerformed

    private void velmaCierreUp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp6ActionPerformed

    private void velmaCierreUp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp7ActionPerformed

    private void velmaCierreUp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp8ActionPerformed

    private void velmaCierreUp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp9ActionPerformed

    private void velmaCierreUp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp10ActionPerformed

    private void velmaCierreUp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaCierreUp11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaCierreUp11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambioValores;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton velmaCierreUp;
    private javax.swing.JButton velmaCierreUp1;
    private javax.swing.JButton velmaCierreUp10;
    private javax.swing.JButton velmaCierreUp11;
    private javax.swing.JButton velmaCierreUp2;
    private javax.swing.JButton velmaCierreUp3;
    private javax.swing.JButton velmaCierreUp4;
    private javax.swing.JButton velmaCierreUp5;
    private javax.swing.JButton velmaCierreUp6;
    private javax.swing.JButton velmaCierreUp7;
    private javax.swing.JButton velmaCierreUp8;
    private javax.swing.JButton velmaCierreUp9;
    private javax.swing.JTextField velmaIntro;
    private javax.swing.JTextField velmaIntro1;
    private javax.swing.JTextField velmaIntro10;
    private javax.swing.JTextField velmaIntro11;
    private javax.swing.JTextField velmaIntro12;
    private javax.swing.JTextField velmaIntro13;
    private javax.swing.JTextField velmaIntro15;
    private javax.swing.JTextField velmaIntro16;
    private javax.swing.JTextField velmaIntro17;
    private javax.swing.JTextField velmaIntro18;
    private javax.swing.JTextField velmaIntro19;
    private javax.swing.JTextField velmaIntro2;
    private javax.swing.JTextField velmaIntro20;
    private javax.swing.JTextField velmaIntro21;
    private javax.swing.JTextField velmaIntro22;
    private javax.swing.JTextField velmaIntro23;
    private javax.swing.JTextField velmaIntro24;
    private javax.swing.JTextField velmaIntro25;
    private javax.swing.JTextField velmaIntro26;
    private javax.swing.JTextField velmaIntro27;
    private javax.swing.JTextField velmaIntro28;
    private javax.swing.JTextField velmaIntro29;
    private javax.swing.JTextField velmaIntro3;
    private javax.swing.JTextField velmaIntro30;
    private javax.swing.JTextField velmaIntro31;
    private javax.swing.JTextField velmaIntro32;
    private javax.swing.JTextField velmaIntro33;
    private javax.swing.JTextField velmaIntro34;
    private javax.swing.JTextField velmaIntro35;
    private javax.swing.JTextField velmaIntro36;
    private javax.swing.JTextField velmaIntro37;
    private javax.swing.JTextField velmaIntro38;
    private javax.swing.JTextField velmaIntro39;
    private javax.swing.JTextField velmaIntro4;
    private javax.swing.JTextField velmaIntro40;
    private javax.swing.JTextField velmaIntro41;
    private javax.swing.JTextField velmaIntro43;
    private javax.swing.JTextField velmaIntro44;
    private javax.swing.JTextField velmaIntro5;
    private javax.swing.JTextField velmaIntro6;
    private javax.swing.JTextField velmaIntro7;
    private javax.swing.JTextField velmaIntro8;
    private javax.swing.JTextField velmaIntro9;
    private javax.swing.JButton velmaIntroDown;
    private javax.swing.JButton velmaIntroDown1;
    private javax.swing.JButton velmaIntroDown10;
    private javax.swing.JButton velmaIntroDown11;
    private javax.swing.JButton velmaIntroDown2;
    private javax.swing.JButton velmaIntroDown3;
    private javax.swing.JButton velmaIntroDown4;
    private javax.swing.JButton velmaIntroDown5;
    private javax.swing.JButton velmaIntroDown6;
    private javax.swing.JButton velmaIntroDown7;
    private javax.swing.JButton velmaIntroDown8;
    private javax.swing.JButton velmaIntroDown9;
    // End of variables declaration//GEN-END:variables
}
