/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animationstudios;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import animationstudios.Actor;
import animationstudios.AnimationStudios;
import animationstudios.Animator;
import animationstudios.Assembler;
import animationstudios.AssemblerDrive;
import animationstudios.Designer;
import animationstudios.Developers;
import animationstudios.Director;
import animationstudios.Drive;
import animationstudios.PlotTwistWriter;
import animationstudios.ProjectManager;
import animationstudios.ScreenWriter;

/**
 *
 * @author juanm
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    int DuracionDias = 86400;
    int CantidadDias = 20; 
    
//    Disney Chanel
    int Guionistas=0;
    int Designers=0;
    int Animadores=0;
    int ActoresD=0;
    int GuionistasPT=0;
    int Ensambladores=0;
    
    Developers devDC = new Developers(CantidadDias,DuracionDias,Guionistas,Animadores,Designers,ActoresD,GuionistasPT,Ensambladores);
    ScreenWriter guionistaD = new ScreenWriter(devDC);
    Designer designerD = new Designer(devDC);
    Animator animadorD = new Animator(devDC);
    Actor actorD = new Actor(devDC);
    PlotTwistWriter plottwistD = new PlotTwistWriter(devDC);
    Assembler ensambladorD = new Assembler(devDC,1,1,2,4);
    
    
    //    Star Chanel
    int GuionistasStarC=0;
    int DesignersStarC=0;
    int AnimadoresStarC=0;
    int ActoresDStarC=0;
    int GuionistasPTStarC=0;
    int EnsambladoresStarC=0;
    
    Developers devSC = new Developers(CantidadDias,DuracionDias,GuionistasStarC,AnimadoresStarC,DesignersStarC,ActoresDStarC,GuionistasPTStarC,EnsambladoresStarC);
    ScreenWriter guionistaS = new ScreenWriter(devSC);
    Designer designerS = new Designer(devSC);
    Animator animadorS = new Animator(devSC);
    Actor actorS = new Actor(devSC);
    PlotTwistWriter plottwistS = new PlotTwistWriter(devSC);
    Assembler ensambladorS = new Assembler(devSC,2,3,4,6);
    
    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CambioValores = new javax.swing.JButton();
        InicioSimulacion = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EnsambladoresDC = new javax.swing.JTextField();
        GuionistasDC = new javax.swing.JTextField();
        DesignersDC = new javax.swing.JTextField();
        AnimadoresDC = new javax.swing.JTextField();
        ActoresDC = new javax.swing.JTextField();
        EnsambladoresSC = new javax.swing.JTextField();
        GuionistasSC = new javax.swing.JTextField();
        DesignersSC = new javax.swing.JTextField();
        AnimadoresSC = new javax.swing.JTextField();
        ActoresSC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        PlotTwistActivosDC = new javax.swing.JTextField();
        GuionesActivosDC = new javax.swing.JTextField();
        EscenariosActivosDC = new javax.swing.JTextField();
        AnimacionesActivasDC = new javax.swing.JTextField();
        DoblajesActivosDC = new javax.swing.JTextField();
        CapacidadPlotTwistDC = new javax.swing.JTextField();
        CapacidadGuionesDC = new javax.swing.JTextField();
        CapacidadEscenariosDC = new javax.swing.JTextField();
        CapacidadAnimacionesDC = new javax.swing.JTextField();
        CapacidadDoblajesDC = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PlotTwistActivosSC = new javax.swing.JTextField();
        GuionesActivosSC = new javax.swing.JTextField();
        EscenariosActivosSC = new javax.swing.JTextField();
        AnimacionesActivasSC = new javax.swing.JTextField();
        DoblajesActivosSC = new javax.swing.JTextField();
        CapacidadPlotTwistSC = new javax.swing.JTextField();
        CapacidadGuionesSC = new javax.swing.JTextField();
        CapacidadEscenariosSC = new javax.swing.JTextField();
        CapacidadAnimacionesSC = new javax.swing.JTextField();
        CapacidadDoblajesSC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        GuionistasPTSC = new javax.swing.JTextField();
        velmaIntro11 = new javax.swing.JTextField();
        GuionistasPTDC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        velmaIntro13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CapitulosTerminadosDC = new javax.swing.JTextField();
        CapitulosTerminadosPTDC = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        CapitulosTerminadosSC = new javax.swing.JTextField();
        CapitulosTerminadosPTSC = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ActividadPM = new javax.swing.JTextField();
        FaltasPM = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        ActividadDirector = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        DescuentoPM = new javax.swing.JTextField();
        SalarioPM = new javax.swing.JTextField();
        DownAnimadoresDC = new javax.swing.JButton();
        DownActoresDC = new javax.swing.JButton();
        DownGuionistasPTDC = new javax.swing.JButton();
        DownDesignersDC = new javax.swing.JButton();
        DownGuionistasDC = new javax.swing.JButton();
        DownDesignersSC = new javax.swing.JButton();
        DownAnimadoresSC = new javax.swing.JButton();
        DownActoresSC = new javax.swing.JButton();
        DownGuionistasPTSC = new javax.swing.JButton();
        DownEnsambladoresSC = new javax.swing.JButton();
        DownGuionistasSC = new javax.swing.JButton();
        UpGuionistasSC = new javax.swing.JButton();
        UpDesignersSC = new javax.swing.JButton();
        UpAnimadoresSC = new javax.swing.JButton();
        UpActoresSC = new javax.swing.JButton();
        UpEnsambladoresDC = new javax.swing.JButton();
        UpEnsambladoresSC = new javax.swing.JButton();
        UpGuionistasPTSC = new javax.swing.JButton();
        UpAnmiadoresDC = new javax.swing.JButton();
        UpDesignersDC = new javax.swing.JButton();
        UpGuionistasDC = new javax.swing.JButton();
        UpActoresDC = new javax.swing.JButton();
        UpGuionistasPTDC = new javax.swing.JButton();
        DownEnsambladoresDC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DISEÑADORES");
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        CambioValores.setText("Colocar Nuevos Valores");
        CambioValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioValoresActionPerformed(evt);
            }
        });
        getContentPane().add(CambioValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        InicioSimulacion.setText("Iniciar simulacion");
        InicioSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSimulacionActionPerformed(evt);
            }
        });
        getContentPane().add(InicioSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 140, -1));

        Titulo.setText("ESTUDIOS DE ANIMACION EN VENEZUELA");
        Titulo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TituloPropertyChange(evt);
            }
        });
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 50));

        jLabel4.setText("DIRECTOR");
        jLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel4PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, -1, 30));

        jLabel9.setText("DISNEY CHANEL");
        jLabel9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel9PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        jLabel5.setText("ANIMADORES");
        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 20));

        jLabel6.setText("ACTORES D");
        jLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel6PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        jLabel7.setText("GUIONISTA PT");
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        jLabel8.setText("GUIONISTAS");
        jLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel8PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        jLabel3.setText("DISEÑADORES");
        jLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel3PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, 20));

        jLabel10.setText("STAR CHANEL");
        jLabel10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel10PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, 30));

        jLabel11.setText("ANIMADORES");
        jLabel11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel11PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 20));

        jLabel12.setText("ACTORES D");
        jLabel12.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel12PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 20));

        jLabel13.setText("GUIONISTA PT");
        jLabel13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel13PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, 20));

        jLabel14.setText("GUIONISTAS");
        jLabel14.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel14PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 20));

        EnsambladoresDC.setEditable(false);
        EnsambladoresDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnsambladoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnsambladoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(EnsambladoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 40, -1));

        GuionistasDC.setEditable(false);
        GuionistasDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionistasDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionistasDCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionistasDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 40, -1));

        DesignersDC.setEditable(false);
        DesignersDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DesignersDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignersDCActionPerformed(evt);
            }
        });
        getContentPane().add(DesignersDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 40, -1));

        AnimadoresDC.setEditable(false);
        AnimadoresDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnimadoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimadoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(AnimadoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 40, -1));

        ActoresDC.setEditable(false);
        ActoresDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(ActoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 40, -1));

        EnsambladoresSC.setEditable(false);
        EnsambladoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnsambladoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnsambladoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(EnsambladoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 40, -1));

        GuionistasSC.setEditable(false);
        GuionistasSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionistasSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionistasSCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionistasSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 40, -1));

        DesignersSC.setEditable(false);
        DesignersSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DesignersSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignersSCActionPerformed(evt);
            }
        });
        getContentPane().add(DesignersSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 40, -1));

        AnimadoresSC.setEditable(false);
        AnimadoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnimadoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimadoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(AnimadoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, -1));

        ActoresSC.setEditable(false);
        ActoresSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(ActoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 40, -1));

        jLabel15.setText("MAX");
        jLabel15.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel15PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 30, 20));

        jLabel21.setText("ESCENARIOS");
        jLabel21.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel21PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 20));

        jLabel22.setText("ANIMACIONES");
        jLabel22.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel22PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 20));

        jLabel23.setText("DOBLAJES");
        jLabel23.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel23PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 20));

        jLabel24.setText("PLOT TWIST");
        jLabel24.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel24PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, 20));

        jLabel25.setText("GUIONES");
        jLabel25.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel25PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 20));

        PlotTwistActivosDC.setEditable(false);
        PlotTwistActivosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlotTwistActivosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotTwistActivosDCActionPerformed(evt);
            }
        });
        getContentPane().add(PlotTwistActivosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 40, -1));

        GuionesActivosDC.setEditable(false);
        GuionesActivosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionesActivosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionesActivosDCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionesActivosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, -1));

        EscenariosActivosDC.setEditable(false);
        EscenariosActivosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EscenariosActivosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscenariosActivosDCActionPerformed(evt);
            }
        });
        getContentPane().add(EscenariosActivosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 40, -1));

        AnimacionesActivasDC.setEditable(false);
        AnimacionesActivasDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnimacionesActivasDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimacionesActivasDCActionPerformed(evt);
            }
        });
        getContentPane().add(AnimacionesActivasDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 40, -1));

        DoblajesActivosDC.setEditable(false);
        DoblajesActivosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DoblajesActivosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoblajesActivosDCActionPerformed(evt);
            }
        });
        getContentPane().add(DoblajesActivosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 40, -1));

        CapacidadPlotTwistDC.setEditable(false);
        CapacidadPlotTwistDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadPlotTwistDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadPlotTwistDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadPlotTwistDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 40, -1));

        CapacidadGuionesDC.setEditable(false);
        CapacidadGuionesDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadGuionesDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadGuionesDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadGuionesDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 40, -1));

        CapacidadEscenariosDC.setEditable(false);
        CapacidadEscenariosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadEscenariosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadEscenariosDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadEscenariosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 40, -1));

        CapacidadAnimacionesDC.setEditable(false);
        CapacidadAnimacionesDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadAnimacionesDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadAnimacionesDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadAnimacionesDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 40, -1));

        CapacidadDoblajesDC.setEditable(false);
        CapacidadDoblajesDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadDoblajesDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadDoblajesDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadDoblajesDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 40, -1));

        jLabel26.setText("ESCENARIOS");
        jLabel26.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel26PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 20));

        jLabel27.setText("ANIMACIONES");
        jLabel27.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel27PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 20));

        jLabel28.setText("DOBLAJES");
        jLabel28.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel28PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, 20));

        jLabel29.setText("PLOT TWIST");
        jLabel29.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel29PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 20));

        jLabel30.setText("GUIONES");
        jLabel30.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel30PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, 20));

        PlotTwistActivosSC.setEditable(false);
        PlotTwistActivosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlotTwistActivosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotTwistActivosSCActionPerformed(evt);
            }
        });
        getContentPane().add(PlotTwistActivosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 40, -1));

        GuionesActivosSC.setEditable(false);
        GuionesActivosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionesActivosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionesActivosSCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionesActivosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 40, -1));

        EscenariosActivosSC.setEditable(false);
        EscenariosActivosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EscenariosActivosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscenariosActivosSCActionPerformed(evt);
            }
        });
        getContentPane().add(EscenariosActivosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 40, -1));

        AnimacionesActivasSC.setEditable(false);
        AnimacionesActivasSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnimacionesActivasSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimacionesActivasSCActionPerformed(evt);
            }
        });
        getContentPane().add(AnimacionesActivasSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 40, -1));

        DoblajesActivosSC.setEditable(false);
        DoblajesActivosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DoblajesActivosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoblajesActivosSCActionPerformed(evt);
            }
        });
        getContentPane().add(DoblajesActivosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 40, -1));

        CapacidadPlotTwistSC.setEditable(false);
        CapacidadPlotTwistSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadPlotTwistSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadPlotTwistSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadPlotTwistSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 40, -1));

        CapacidadGuionesSC.setEditable(false);
        CapacidadGuionesSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadGuionesSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadGuionesSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadGuionesSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 40, -1));

        CapacidadEscenariosSC.setEditable(false);
        CapacidadEscenariosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadEscenariosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadEscenariosSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadEscenariosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 40, -1));

        CapacidadAnimacionesSC.setEditable(false);
        CapacidadAnimacionesSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadAnimacionesSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadAnimacionesSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadAnimacionesSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 40, -1));

        CapacidadDoblajesSC.setEditable(false);
        CapacidadDoblajesSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapacidadDoblajesSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadDoblajesSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadDoblajesSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 40, -1));

        jLabel16.setText("ENSAMBLADORES");
        jLabel16.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel16PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, 30));

        jLabel17.setText("MAX");
        jLabel17.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel17PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 30, 20));

        jLabel18.setText("TRABAJADORES");
        jLabel18.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel18PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));

        GuionistasPTSC.setEditable(false);
        GuionistasPTSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionistasPTSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionistasPTSCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionistasPTSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        velmaIntro11.setEditable(false);
        velmaIntro11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro11ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        GuionistasPTDC.setEditable(false);
        GuionistasPTDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuionistasPTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuionistasPTDCActionPerformed(evt);
            }
        });
        getContentPane().add(GuionistasPTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 40, -1));

        jLabel19.setText("ENSAMBLADORES");
        jLabel19.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel19PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 30));

        velmaIntro13.setEditable(false);
        velmaIntro13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        velmaIntro13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaIntro13ActionPerformed(evt);
            }
        });
        getContentPane().add(velmaIntro13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 40, -1));

        jLabel20.setText("ELEMENTOS DE CAPITULOS");
        jLabel20.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel20PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 30));

        jLabel31.setText("PLOT TWIST");
        jLabel31.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel31PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, 20));

        jLabel32.setText("ESTANDAR");
        jLabel32.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel32PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 20));

        CapitulosTerminadosDC.setEditable(false);
        CapitulosTerminadosDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapitulosTerminadosDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitulosTerminadosDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapitulosTerminadosDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 40, -1));

        CapitulosTerminadosPTDC.setEditable(false);
        CapitulosTerminadosPTDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapitulosTerminadosPTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitulosTerminadosPTDCActionPerformed(evt);
            }
        });
        getContentPane().add(CapitulosTerminadosPTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 40, -1));

        jLabel33.setText("PLOT TWIST");
        jLabel33.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel33PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, -1, 20));

        jLabel34.setText("ESTANDAR");
        jLabel34.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel34PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, 20));

        CapitulosTerminadosSC.setEditable(false);
        CapitulosTerminadosSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapitulosTerminadosSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitulosTerminadosSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapitulosTerminadosSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 40, -1));

        CapitulosTerminadosPTSC.setEditable(false);
        CapitulosTerminadosPTSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapitulosTerminadosPTSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitulosTerminadosPTSCActionPerformed(evt);
            }
        });
        getContentPane().add(CapitulosTerminadosPTSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 40, -1));

        jLabel35.setText("FALTAS");
        jLabel35.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel35PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, -1, 20));

        jLabel36.setText("ACTIVIDAD");
        jLabel36.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel36PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, 20));

        ActividadPM.setEditable(false);
        ActividadPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActividadPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActividadPMActionPerformed(evt);
            }
        });
        getContentPane().add(ActividadPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 70, -1));

        FaltasPM.setEditable(false);
        FaltasPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FaltasPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaltasPMActionPerformed(evt);
            }
        });
        getContentPane().add(FaltasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 70, -1));

        jLabel38.setText("ACTIVIDAD");
        jLabel38.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel38PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, 20));

        ActividadDirector.setEditable(false);
        ActividadDirector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActividadDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActividadDirectorActionPerformed(evt);
            }
        });
        getContentPane().add(ActividadDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 80, -1));

        jLabel39.setText("ELEMENTOS DE CAPITULOS");
        jLabel39.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel39PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, 30));

        jLabel40.setText("PROJECT MANAGER");
        jLabel40.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel40PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, 30));

        jLabel41.setText("SALARIO");
        jLabel41.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel41PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, -1, 20));

        jLabel42.setText("DESCUENTO");
        jLabel42.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel42PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, -1, 20));

        DescuentoPM.setEditable(false);
        DescuentoPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DescuentoPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescuentoPMActionPerformed(evt);
            }
        });
        getContentPane().add(DescuentoPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 70, -1));

        SalarioPM.setEditable(false);
        SalarioPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SalarioPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioPMActionPerformed(evt);
            }
        });
        getContentPane().add(SalarioPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, 70, -1));

        DownAnimadoresDC.setText("-");
        DownAnimadoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownAnimadoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownAnimadoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        DownActoresDC.setText("-");
        DownActoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownActoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        DownGuionistasPTDC.setText("-");
        DownGuionistasPTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownGuionistasPTDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownGuionistasPTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        DownDesignersDC.setText("-");
        DownDesignersDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownDesignersDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownDesignersDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        DownGuionistasDC.setText("-");
        DownGuionistasDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownGuionistasDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownGuionistasDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        DownDesignersSC.setText("-");
        DownDesignersSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownDesignersSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownDesignersSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        DownAnimadoresSC.setText("-");
        DownAnimadoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownAnimadoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownAnimadoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        DownActoresSC.setText("-");
        DownActoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownActoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        DownGuionistasPTSC.setText("-");
        DownGuionistasPTSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownGuionistasPTSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownGuionistasPTSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        DownEnsambladoresSC.setText("-");
        DownEnsambladoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownEnsambladoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownEnsambladoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        DownGuionistasSC.setText("-");
        DownGuionistasSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownGuionistasSCActionPerformed(evt);
            }
        });
        getContentPane().add(DownGuionistasSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        UpGuionistasSC.setText("+");
        UpGuionistasSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpGuionistasSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpGuionistasSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        UpDesignersSC.setText("+");
        UpDesignersSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpDesignersSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpDesignersSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        UpAnimadoresSC.setText("+");
        UpAnimadoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpAnimadoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpAnimadoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        UpActoresSC.setText("+");
        UpActoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpActoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        UpEnsambladoresDC.setText("+");
        UpEnsambladoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpEnsambladoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpEnsambladoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        UpEnsambladoresSC.setText("+");
        UpEnsambladoresSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpEnsambladoresSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpEnsambladoresSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        UpGuionistasPTSC.setText("+");
        UpGuionistasPTSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpGuionistasPTSCActionPerformed(evt);
            }
        });
        getContentPane().add(UpGuionistasPTSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        UpAnmiadoresDC.setText("+");
        UpAnmiadoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpAnmiadoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpAnmiadoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        UpDesignersDC.setText("+");
        UpDesignersDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpDesignersDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpDesignersDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        UpGuionistasDC.setText("+");
        UpGuionistasDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpGuionistasDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpGuionistasDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        UpActoresDC.setText("+");
        UpActoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpActoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        UpGuionistasPTDC.setText("+");
        UpGuionistasPTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpGuionistasPTDCActionPerformed(evt);
            }
        });
        getContentPane().add(UpGuionistasPTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        DownEnsambladoresDC.setText("-");
        DownEnsambladoresDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownEnsambladoresDCActionPerformed(evt);
            }
        });
        getContentPane().add(DownEnsambladoresDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void CambioValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioValoresActionPerformed
        // TODO add your handling code here:
        int inputDuracionDias = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el tiempo que dura un dia en segundos: "));
        int inputCantidadDias = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese la cantidad de dias entre lanzamientos: "));
        
//      Disney Chanel
        int inputGuionistas = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de guionistas de Disney Chanel: "));
        int inputDesigners = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de diseñadores de Disney Chanel: "));
        int inputAnimadores = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de animadores de personajes de Disney Chanel: "));
        int inputActoresD = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de actores de doblaje de Disney Chanel: "));
        int inputGuionistasPT = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de guionistas de Plot twist de Disney Chanel: "));
        int inputEnsambladores = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de ensambladores de Disney Chanel: "));
        
//      Star Chanel
        int inputGuionistasStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de guionistas de Star Chanel: "));
        int inputDesignersStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de diseñadores de Star Chanel: "));
        int inputAnimadoresStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de animadores de personajes de Star Chanel: "));
        int inputActoresDStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de actores de doblaje de Star Chanel: "));
        int inputGuionistasPTStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de guionistas de Plot twist de Star Chanel: "));
        int inputEnsambladoresStarC = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de ensambladores de Star Chanel: "));

        String archivotxt = inputDuracionDias + "//" + inputCantidadDias + "//" + inputGuionistas + "," + inputDesigners + "," + inputAnimadores + "," + inputActoresD + "," + inputGuionistasPT + "," + inputEnsambladores + "//" + inputGuionistasStarC + "," + inputDesignersStarC + "," + inputAnimadoresStarC + "," + inputActoresDStarC + "," + inputGuionistasPTStarC + "," + inputEnsambladoresStarC;
        
        try {
            PrintStream out = new PrintStream(new FileOutputStream("archivo.txt"));
            out.print(archivotxt);
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_CambioValoresActionPerformed

    private void InicioSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSimulacionActionPerformed
        // TODO add your handling code here:
        BufferedReader br;
        try{
            br = new BufferedReader(new FileReader("config.txt"));
            String datos = br.readLine();
            String[] datoSplit = datos.split("//");
            String[] trabajadoresDC = datoSplit[2].split(",");
            String[] trabajadoresSC = datoSplit[3].split(",");
            
            DuracionDias = Integer.parseInt(datoSplit[0]);
            CantidadDias = Integer.parseInt(datoSplit[1]);
            
            Guionistas = Integer.parseInt(trabajadoresDC[0]);
            Designers = Integer.parseInt(trabajadoresDC[1]);
            Animadores = Integer.parseInt(trabajadoresDC[2]);
            ActoresD = Integer.parseInt(trabajadoresDC[3]);
            GuionistasPT = Integer.parseInt(trabajadoresDC[4]);
            Ensambladores = Integer.parseInt(trabajadoresDC[5]);
            
            devDC.setDaysLeft(CantidadDias);
            devDC.setDayDuration(DuracionDias);
            devDC.setSwAmount(Guionistas);
            devDC.setDesignerAmount(Designers);
            devDC.setAnimatorAmount(Animadores);
            devDC.setActorAmount(ActoresD);
            devDC.setPtAmount(GuionistasPT);
            devDC.setAssemblerAmount(Ensambladores);
            
            guionistaD.setDev(devDC);
            designerD.setDev(devDC);
            animadorD.setDev(devDC);
            actorD.setDev(devDC);
            plottwistD.setDev(devDC);
            ensambladorD.setDev(devDC);
            
            
            
            GuionistasStarC = Integer.parseInt(trabajadoresSC[0]);
            DesignersStarC = Integer.parseInt(trabajadoresSC[1]);
            AnimadoresStarC = Integer.parseInt(trabajadoresSC[2]);
            ActoresDStarC = Integer.parseInt(trabajadoresSC[3]);
            GuionistasPTStarC = Integer.parseInt(trabajadoresSC[4]);
            EnsambladoresStarC = Integer.parseInt(trabajadoresSC[5]);
            
            devSC.setDaysLeft(CantidadDias);
            devSC.setDayDuration(DuracionDias);
            devSC.setSwAmount(GuionistasStarC);
            devSC.setDesignerAmount(DesignersStarC);
            devSC.setAnimatorAmount(AnimadoresStarC);
            devSC.setActorAmount(ActoresDStarC);
            devSC.setPtAmount(GuionistasPTStarC);
            devSC.setAssemblerAmount(EnsambladoresStarC);
            
            guionistaS.setDev(devSC);
            designerS.setDev(devSC);
            animadorS.setDev(devSC);
            actorS.setDev(devSC);
            plottwistS.setDev(devSC);
            ensambladorS.setDev(devSC);
            
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_InicioSimulacionActionPerformed

    private void TituloPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TituloPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloPropertyChange

    private void jLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4PropertyChange

    private void jLabel9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel9PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9PropertyChange

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5PropertyChange

    private void jLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6PropertyChange

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7PropertyChange

    private void jLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8PropertyChange

    private void jLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3PropertyChange

    private void jLabel10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel10PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10PropertyChange

    private void jLabel11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel11PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11PropertyChange

    private void jLabel12PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel12PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12PropertyChange

    private void jLabel13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel13PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13PropertyChange

    private void jLabel14PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel14PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14PropertyChange

    private void EnsambladoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnsambladoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnsambladoresDCActionPerformed

    private void GuionistasDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionistasDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionistasDCActionPerformed

    private void DesignersDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignersDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignersDCActionPerformed

    private void AnimadoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimadoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimadoresDCActionPerformed

    private void ActoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActoresDCActionPerformed

    private void EnsambladoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnsambladoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnsambladoresSCActionPerformed

    private void GuionistasSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionistasSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionistasSCActionPerformed

    private void DesignersSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignersSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignersSCActionPerformed

    private void AnimadoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimadoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimadoresSCActionPerformed

    private void ActoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActoresSCActionPerformed

    private void jLabel15PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel15PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15PropertyChange

    private void jLabel21PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel21PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21PropertyChange

    private void jLabel22PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel22PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22PropertyChange

    private void jLabel23PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel23PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23PropertyChange

    private void jLabel24PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel24PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24PropertyChange

    private void jLabel25PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel25PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25PropertyChange

    private void PlotTwistActivosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotTwistActivosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlotTwistActivosDCActionPerformed

    private void GuionesActivosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionesActivosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionesActivosDCActionPerformed

    private void EscenariosActivosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscenariosActivosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscenariosActivosDCActionPerformed

    private void AnimacionesActivasDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimacionesActivasDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimacionesActivasDCActionPerformed

    private void DoblajesActivosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoblajesActivosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoblajesActivosDCActionPerformed

    private void CapacidadPlotTwistDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadPlotTwistDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadPlotTwistDCActionPerformed

    private void CapacidadGuionesDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadGuionesDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadGuionesDCActionPerformed

    private void CapacidadEscenariosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadEscenariosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadEscenariosDCActionPerformed

    private void CapacidadAnimacionesDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadAnimacionesDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadAnimacionesDCActionPerformed

    private void CapacidadDoblajesDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadDoblajesDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadDoblajesDCActionPerformed

    private void jLabel26PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel26PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26PropertyChange

    private void jLabel27PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel27PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27PropertyChange

    private void jLabel28PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel28PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28PropertyChange

    private void jLabel29PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel29PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29PropertyChange

    private void jLabel30PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel30PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30PropertyChange

    private void PlotTwistActivosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotTwistActivosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlotTwistActivosSCActionPerformed

    private void GuionesActivosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionesActivosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionesActivosSCActionPerformed

    private void EscenariosActivosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscenariosActivosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscenariosActivosSCActionPerformed

    private void AnimacionesActivasSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimacionesActivasSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimacionesActivasSCActionPerformed

    private void DoblajesActivosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoblajesActivosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoblajesActivosSCActionPerformed

    private void CapacidadPlotTwistSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadPlotTwistSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadPlotTwistSCActionPerformed

    private void CapacidadGuionesSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadGuionesSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadGuionesSCActionPerformed

    private void CapacidadEscenariosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadEscenariosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadEscenariosSCActionPerformed

    private void CapacidadAnimacionesSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadAnimacionesSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadAnimacionesSCActionPerformed

    private void CapacidadDoblajesSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadDoblajesSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadDoblajesSCActionPerformed

    private void jLabel16PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel16PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16PropertyChange

    private void jLabel17PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel17PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17PropertyChange

    private void jLabel18PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel18PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18PropertyChange

    private void GuionistasPTSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionistasPTSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionistasPTSCActionPerformed

    private void velmaIntro11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro11ActionPerformed

    private void GuionistasPTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuionistasPTDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuionistasPTDCActionPerformed

    private void jLabel19PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel19PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19PropertyChange

    private void velmaIntro13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaIntro13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velmaIntro13ActionPerformed

    private void jLabel20PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel20PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20PropertyChange

    private void jLabel31PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel31PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31PropertyChange

    private void jLabel32PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel32PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32PropertyChange

    private void CapitulosTerminadosDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitulosTerminadosDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapitulosTerminadosDCActionPerformed

    private void CapitulosTerminadosPTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitulosTerminadosPTDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapitulosTerminadosPTDCActionPerformed

    private void jLabel33PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel33PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33PropertyChange

    private void jLabel34PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel34PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34PropertyChange

    private void CapitulosTerminadosSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitulosTerminadosSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapitulosTerminadosSCActionPerformed

    private void CapitulosTerminadosPTSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitulosTerminadosPTSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapitulosTerminadosPTSCActionPerformed

    private void jLabel35PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel35PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35PropertyChange

    private void jLabel36PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel36PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36PropertyChange

    private void ActividadPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActividadPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActividadPMActionPerformed

    private void FaltasPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaltasPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaltasPMActionPerformed

    private void jLabel38PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel38PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38PropertyChange

    private void ActividadDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActividadDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActividadDirectorActionPerformed

    private void jLabel39PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel39PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39PropertyChange

    private void jLabel40PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel40PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40PropertyChange

    private void jLabel41PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel41PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41PropertyChange

    private void jLabel42PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel42PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42PropertyChange

    private void DescuentoPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuentoPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescuentoPMActionPerformed

    private void SalarioPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioPMActionPerformed

    private void DownAnimadoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownAnimadoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownAnimadoresDCActionPerformed

    private void DownActoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownActoresDCActionPerformed

    private void DownGuionistasPTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownGuionistasPTDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownGuionistasPTDCActionPerformed

    private void DownDesignersDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownDesignersDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownDesignersDCActionPerformed

    private void DownGuionistasDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownGuionistasDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownGuionistasDCActionPerformed

    private void DownDesignersSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownDesignersSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownDesignersSCActionPerformed

    private void DownAnimadoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownAnimadoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownAnimadoresSCActionPerformed

    private void DownActoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownActoresSCActionPerformed

    private void DownGuionistasPTSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownGuionistasPTSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownGuionistasPTSCActionPerformed

    private void DownEnsambladoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownEnsambladoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownEnsambladoresSCActionPerformed

    private void DownGuionistasSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownGuionistasSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownGuionistasSCActionPerformed

    private void UpGuionistasSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpGuionistasSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpGuionistasSCActionPerformed

    private void UpDesignersSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpDesignersSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpDesignersSCActionPerformed

    private void UpAnimadoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpAnimadoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpAnimadoresSCActionPerformed

    private void UpActoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpActoresSCActionPerformed

    private void UpEnsambladoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpEnsambladoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpEnsambladoresDCActionPerformed

    private void UpEnsambladoresSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpEnsambladoresSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpEnsambladoresSCActionPerformed

    private void UpGuionistasPTSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpGuionistasPTSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpGuionistasPTSCActionPerformed

    private void UpAnmiadoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpAnmiadoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpAnmiadoresDCActionPerformed

    private void UpDesignersDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpDesignersDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpDesignersDCActionPerformed

    private void UpGuionistasDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpGuionistasDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpGuionistasDCActionPerformed

    private void UpActoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpActoresDCActionPerformed

    private void UpGuionistasPTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpGuionistasPTDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpGuionistasPTDCActionPerformed

    private void DownEnsambladoresDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownEnsambladoresDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DownEnsambladoresDCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActividadDirector;
    private javax.swing.JTextField ActividadPM;
    private javax.swing.JTextField ActoresDC;
    private javax.swing.JTextField ActoresSC;
    private javax.swing.JTextField AnimacionesActivasDC;
    private javax.swing.JTextField AnimacionesActivasSC;
    private javax.swing.JTextField AnimadoresDC;
    private javax.swing.JTextField AnimadoresSC;
    private javax.swing.JButton CambioValores;
    private javax.swing.JTextField CapacidadAnimacionesDC;
    private javax.swing.JTextField CapacidadAnimacionesSC;
    private javax.swing.JTextField CapacidadDoblajesDC;
    private javax.swing.JTextField CapacidadDoblajesSC;
    private javax.swing.JTextField CapacidadEscenariosDC;
    private javax.swing.JTextField CapacidadEscenariosSC;
    private javax.swing.JTextField CapacidadGuionesDC;
    private javax.swing.JTextField CapacidadGuionesSC;
    private javax.swing.JTextField CapacidadPlotTwistDC;
    private javax.swing.JTextField CapacidadPlotTwistSC;
    private javax.swing.JTextField CapitulosTerminadosDC;
    private javax.swing.JTextField CapitulosTerminadosPTDC;
    private javax.swing.JTextField CapitulosTerminadosPTSC;
    private javax.swing.JTextField CapitulosTerminadosSC;
    private javax.swing.JTextField DescuentoPM;
    private javax.swing.JTextField DesignersDC;
    private javax.swing.JTextField DesignersSC;
    private javax.swing.JTextField DoblajesActivosDC;
    private javax.swing.JTextField DoblajesActivosSC;
    private javax.swing.JButton DownActoresDC;
    private javax.swing.JButton DownActoresSC;
    private javax.swing.JButton DownAnimadoresDC;
    private javax.swing.JButton DownAnimadoresSC;
    private javax.swing.JButton DownDesignersDC;
    private javax.swing.JButton DownDesignersSC;
    private javax.swing.JButton DownEnsambladoresDC;
    private javax.swing.JButton DownEnsambladoresSC;
    private javax.swing.JButton DownGuionistasDC;
    private javax.swing.JButton DownGuionistasPTDC;
    private javax.swing.JButton DownGuionistasPTSC;
    private javax.swing.JButton DownGuionistasSC;
    private javax.swing.JTextField EnsambladoresDC;
    private javax.swing.JTextField EnsambladoresSC;
    private javax.swing.JTextField EscenariosActivosDC;
    private javax.swing.JTextField EscenariosActivosSC;
    private javax.swing.JTextField FaltasPM;
    private javax.swing.JTextField GuionesActivosDC;
    private javax.swing.JTextField GuionesActivosSC;
    private javax.swing.JTextField GuionistasDC;
    private javax.swing.JTextField GuionistasPTDC;
    private javax.swing.JTextField GuionistasPTSC;
    private javax.swing.JTextField GuionistasSC;
    private javax.swing.JButton InicioSimulacion;
    private javax.swing.JTextField PlotTwistActivosDC;
    private javax.swing.JTextField PlotTwistActivosSC;
    private javax.swing.JTextField SalarioPM;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton UpActoresDC;
    private javax.swing.JButton UpActoresSC;
    private javax.swing.JButton UpAnimadoresSC;
    private javax.swing.JButton UpAnmiadoresDC;
    private javax.swing.JButton UpDesignersDC;
    private javax.swing.JButton UpDesignersSC;
    private javax.swing.JButton UpEnsambladoresDC;
    private javax.swing.JButton UpEnsambladoresSC;
    private javax.swing.JButton UpGuionistasDC;
    private javax.swing.JButton UpGuionistasPTDC;
    private javax.swing.JButton UpGuionistasPTSC;
    private javax.swing.JButton UpGuionistasSC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField velmaIntro11;
    private javax.swing.JTextField velmaIntro13;
    // End of variables declaration//GEN-END:variables
}
